#!/bin/bash -e
# Registers hubbard as a service via init.d
# To be run as sudo

set -x

cd "$(dirname ${BASH_SOURCE[0]})"
cp ./pkg/linux-amd64/hubbard /usr/bin/hubbard
chmod +x /usr/bin/hubbard
useradd hubbard --password ""
chown hubbard /usr/bin/hubbard
chgrp hubbard /usr/bin/hubbard
mkdir -p /etc/hubbard
chgrp -R hubbard /etc/hubbard
chown -R hubbard /etc/hubbard
hubbard configure --github-url=$GITHUB_URL --github-access-token=$GITHUB_ACCESS_TOKEN
cp ./hubbard-service-def /etc/init.d/hubbard
chmod +x /etc/init.d/hubbard
update-rc.d hubbard defaults
service hubbard start
