#!/bin/bash -e
# Registers hubbard as a service via init.d
# To be run as sudo

set -x

cd "$(dirname ${BASH_SOURCE[0]})"
chmod +x ./hubbard
useradd hubbard --password ""
chown hubbard hubbard
chgrp hubbard hubbard
mkdir -p /etc/hubbard
chgrp -R hubbard /etc/hubbard
chown -R hubbard /etc/hubbard
./hubbard configure --github-url=$GITHUB_URL --github-access-token=$GITHUB_ACCESS_TOKEN
cp hubbard /usr/bin/hubbard
cp ./hubbard-service-def /etc/init.d/hubbard
chmod +x /etc/init.d/hubbard
update-rc.d hubbard defaults
service hubbard start
