#!/bin/bash

GIT_CURL_VERBOSE=1 git clone http://localhost:41968/212595461/private_test.git
rm -rf private_test

curl -v http://localhost:41968/raw/212595461/private_test/master/README.md

wget http://localhost:41968/212595461/private_test/releases/download/1.0/private_test.tar.gz